application: chromedevsummit-site
version: v20141125

runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /devsummit
  script: redirector.app
  secure: always

- url: /devsummit/
  script: template.app
  secure: always

- url: /devsummit/images/(.*)
  static_files: dist/static/images/\1
  expiration: "365d"
  upload: dist/static/images/(.*)
  secure: always

- url: /devsummit/sw.js
  static_files: dist/static/scripts/sw.js
  expiration: "1s"
  upload: dist/static/scripts/sw.js
  secure: always

- url: /devsummit/manifest.json
  static_files: dist/manifest.json
  expiration: "1s"
  upload: dist/manifest.json
  secure: always

- url: /devsummit/scripts/(.*)
  static_files: dist/static/scripts/\1
  expiration: "1d"
  upload: dist/static/scripts/(.*)
  secure: always

- url: /devsummit/styles/(.*)
  static_files: dist/static/styles/\1
  expiration: "1d"
  upload: dist/static/styles/(.*)
  secure: always

- url: /devsummit/LICENSE
  static_files: dist/LICENSE
  expiration: "7d"
  mime_type: text/plain
  upload: dist/LICENSE
  secure: always

- url: /devsummit/(.*)
  script: template.app
  secure: always

- url: /src/(.*)
  static_files: src/\1
  upload: src/(.*)
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

pagespeed:
  disabled_rewriters:
  - add_instrumentation
  - CombineJs
  - ConvertMetaTags
  - FallbackRewriteCssUrls
  - FlattenCssImports
  - FlushSubresources
  - ImageConvertGifToPng
  - ImageConvertToJpeg
  - ImageConvertToWebpLossless
  - ImageResize
  - InlineImages
  - InlineImportToLink
  - InlinePreviewImages
  - InsertDnsPrefetch
  - JsOptimize
  - LazyloadImages
  - MinifyCss
  - MoveCssToHead
  - ProxyCss
  - ProxyImages
  - ProxyJs
  enabled_rewriters:
  - CombineCss
  - InlineCss
  - WebpOptimization
  - PrioritizeCriticalCss
  - ImageJpegSubsampling
  - ImageProgressiveJpeg
  - ImageRecompressJpeg
  - ImageRecompressPng
  - ImageStripColorProfile
  - ImageStripMetadata
